---
title: "Reading_score"
author: "Kangyu Xu (kx2224)"
date: "2024-12-08"
output: github_document
---

```{r}
library(tidyverse)
library(broom)
```
## Data Preparation
```{r}
df = read_csv("data/Project_1_data.csv")

score_df = df %>% 
  janitor::clean_names() %>% 
  mutate(across(where(is.character), as.factor))

score_df_sib <- score_df %>%
  mutate(nr_siblings = as.factor(nr_siblings))

# Check for missing values
colSums(is.na(score_df))
```

```{r}
score_df_omit = score_df|> 
  na.omit()

score_df_mean = score_df|>
  mutate(across(where(is.numeric), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .))) |>
   na.omit()

score_df_sib_mean = score_df_sib|>
  mutate(across(where(is.numeric), ~ ifelse(is.na(.), mean(., na.rm = TRUE), .))) |>
   na.omit()
  
```

```{r}
score_df_mean
```
## Build model
```{r}
model_without<- lm(reading_score ~ gender + ethnic_group + parent_educ +
                     lunch_type + test_prep + parent_marital_status + 
                     practice_sport + is_first_child + nr_siblings + 
                     transport_means + wkly_study_hours,
                   data = score_df_omit)
model_with =  lm(reading_score ~ gender + ethnic_group + parent_educ +
                     lunch_type + test_prep + parent_marital_status + 
                     practice_sport + is_first_child + nr_siblings + 
                     transport_means + wkly_study_hours + math_score +
                     writing_score,
                   data = score_df_omit)

```

```{r}
summary(model_with)
```
```{r}
summary(model_without)
```


## Analyse variables
```{r}
significant_vars <- summary(model_without)$coefficients %>%
  as.data.frame() %>%
  rownames_to_column("Variable") %>%
  filter(`Pr(>|t|)` < 0.05) %>%
  arrange(`Pr(>|t|)`)

print("显著变量：")
print(significant_vars)
```

```{r}
interaction_model <- step(lm(reading_score ~ gender + ethnic_group + parent_educ + lunch_type +
                               test_prep + practice_sport + wkly_study_hours +
                               gender:wkly_study_hours + test_prep:wkly_study_hours +
                               parent_educ:lunch_type, 
                             data = score_df_omit))
summary(interaction_model)
```

