---
title: "Writing Scores Analysis"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(MASS)
```


## Import and Clean the Data
```{r}
writing = read.csv(file = "./data/Project_1_data.csv") |> 
  janitor::clean_names() |> 
  mutate(across(where(is.character), ~na_if(.x, "")))
  
writing = writing |> 
  filter(!is.na(writing_score)) |> 
  drop_na()

head(writing)
```


## Descriptive Statistics
```{r}
summary(writing$writing_score)

var(writing$writing_score)
sd(writing$writing_score)
```


## Percentiles
```{r}
percentiles = quantile(writing$writing_score, probs = seq(0.1, 1, by = 0.1))

print(percentiles)
```


## Visualizations
```{r}
ggplot(writing, aes(x = writing_score)) +
  geom_histogram(binwidth = 5, fill = "blue", color = "black", alpha = 0.7) +
  labs(
    title = "Distribution of Writing Scores",
    x = "Score",
    y = "Frequency")
```

```{r}
ggplot(writing, aes(x = writing_score)) +
  geom_density(fill = "purple", alpha = 0.5) +
  labs(
    title = "Density Plot of Writing Scores",
    x = "Writing Score",
    y = "Density")
```

```{r}
ggplot(writing, aes(x = gender, y = writing_score)) +
  geom_boxplot(fill = "lightblue") +
  labs(
    title = "Writing Scores by Gender",
    x = "Gender",
    y = "Writing Score")
```


```{r}
ggplot(writing, aes(x = ethnic_group, y = writing_score)) +
  geom_boxplot(fill = "lightgreen") +
  labs(
    title = "Writing Scores by Ethnic Group",
    x = "Ethnic Group",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = parent_educ, y = writing_score)) +
  geom_boxplot(fill = "lightpink") +
  labs(
    title = "Writing Scores by Parent Education",
    x = "Parent Education",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = lunch_type, y = writing_score)) +
  geom_boxplot(fill = "yellow") +
  labs(
    title = "Writing Scores by Lunch Type",
    x = "Lunch Type",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = test_prep, y = writing_score)) +
  geom_boxplot(fill = "orange") +
  labs(
    title = "Writing Scores by Test Prep",
    x = "Test Prep",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = parent_marital_status, y = writing_score)) +
  geom_boxplot(fill = "navyblue") +
  labs(
    title = "Writing Scores by Parent Marital Status",
    x = "Parent Marital Status",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = practice_sport, y = writing_score)) +
  geom_boxplot(fill = "thistle") +
  labs(
    title = "Writing Scores by Practice Sport",
    x = "Practice Sport",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = is_first_child, y = writing_score)) +
  geom_boxplot(fill = "sienna") +
  labs(
    title = "Writing Scores by First Child",
    x = "First Child",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = nr_siblings, y = writing_score)) +
  geom_boxplot(fill = "salmon") +
  labs(
    title = "Writing Scores by Number of Siblings",
    x = "Number of Siblings",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = transport_means, y = writing_score)) +
  geom_boxplot(fill = "royalblue") +
  labs(
    title = "Writing Scores by Transportation Means",
    x = "Transportation Means",
    y = "Writing Score")
```

```{r}
ggplot(writing, aes(x = wkly_study_hours, y = writing_score)) +
  geom_boxplot(fill = "orchid") +
  labs(
    title = "Writing Scores by Weekly Study Hours",
    x = "Weekly Study Hours",
    y = "Writing Score")
```

## Statistical Testing

### Linear Regression 
```{r}
lm_model = lm(writing_score ~ gender + ethnic_group + parent_educ + lunch_type + test_prep + parent_marital_status + practice_sport + is_first_child + nr_siblings + transport_means + wkly_study_hours, data = writing)

summary(lm_model)
```

### Correlation Matrix
```{r}
writing = writing |> 
  mutate(across(c(gender, ethnic_group, parent_educ, lunch_type, test_prep, parent_marital_status, practice_sport, is_first_child, nr_siblings, transport_means, wkly_study_hours), as.factor))

writing_encoded = writing |> 
  mutate(across(where(is.factor), as.numeric))

cor_writing = writing_encoded |> 
  select_if(is.numeric)

cor_matrix = cor(cor_writing, use = "complete.obs", method = "pearson")

print(cor_matrix)
```

```{r}
cor_table = knitr::kable(cor_matrix, format = "markdown")

print(cor_table)
```

### Backward Elimination Method
```{r}
full_model = lm(writing_score ~ gender + ethnic_group + parent_educ + lunch_type + test_prep + parent_marital_status + practice_sport + is_first_child + nr_siblings + transport_means + wkly_study_hours, data = writing)

backward_model = step(full_model, direction = "backward")

summary(backward_model)
```

Forward Selection
```{r}
empty_model = lm(writing_score ~ 1, data = writing)

forward_model = step(empty_model, 
                     scope = list(lower = empty_model, 
                                  upper = ~ gender + ethnic_group + parent_educ + lunch_type + test_prep + parent_marital_status + practice_sport + is_first_child + nr_siblings + transport_means + wkly_study_hours), direction = "forward")

summary(forward_model)
```


### Stepwise Method (stepAIC)
```{r}
null_model = lm(writing_score ~ 1, data = writing)

stepwise_model = stepAIC(full_model, direction = "both", trace = TRUE)

summary(stepwise_model)
```

